apiVersion: batch/v1
kind: CronJob
metadata:
  name: cache-sync-job
spec:
  schedule: "0 0 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sa-cache-sync
            image: registry.cgraaaj.in/stock-x/stockx-fo-cache:latest
            command: ["python", "sa-cache-manager.py"]
            env:
              - name: IGNITE_HOST
                value: 192.168.1.72
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          restartPolicy: OnFailure
