apiVersion: batch/v1
kind: CronJob
metadata:
  name: cache-sync-job
spec:
  schedule: "0 0 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sa-cache-sync
            image: registry.cgraaaj.in/stock-x/stockx-fo-cache:1.0
            command: ["python", "sa-cache-manager.py"]
          restartPolicy: OnFailure
